# Generated by Django 5.0.6 on 2024-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillxchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='limit',
            field=models.IntegerField(default=10),
        ),
    ]
