# Generated by Django 5.0.6 on 2024-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillxchange', '0002_alter_customuser_username_alter_skills_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='current_students',
            field=models.IntegerField(default=0),
        ),
    ]
