# Generated by Django 5.0.6 on 2024-07-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillxchange', '0003_skills_current_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled',
        ),
    ]
